### ISSUE TITLE
Guide to clone the project.

### ISSUE THREAD

**Issue by E-fais** [krupalitrivedi/calculator#6]
It would be better if you update README file  by providing  guideline  to clone this project as follows,
Clone this project in local machine (Git must be installed in your machine) Open terminal and run the following command
     " git clone https://github.com/krupalitrivedi/calculator.git "

**Comment by krupalitrivedi** [comment]
Hi! Thank you for the issue!

Thank you so much for your suggestion!

Would you like to work on the same and make a contribution? I will make the change otherwise :)

**Comment by E-fais** [comment]
Hi, I would like to work on this issue , if it is still open.

**Comment by krupalitrivedi** [comment]
There you go :)
